### ISSUE TITLE
UnicodeDecodeError on tox

### ISSUE THREAD

**Issue by kanghyojun** [spoqa/iso-3166-1#8]
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 23: ordinal not in range(128)` raised, in `read_from_csv`

**Comment by valericus** [comment]
@admire93, please give some more details about your problem. What python version do you use? How do you start tests? Can you give full log of tests? I've just lunched tox and all tests have passed successfully.

**Comment by kanghyojun** [comment]
@valericus it's happend when try to use `tox` on other private package requires `iso-3166-1`. although all tests have passed successfully. so i'll probably fix this issue in this week.

**Comment by kanghyojun** [comment]
Close issue. since i can't reproduce `UnicodeDecodeError` anymore.
